name: otp_phone_verify
description: A beautiful and customizable Flutter package for phone number verification using OTP with popup dialog. Supports multiple languages (Arabic, French, Spanish) and responsive design.
version: 1.0.2
homepage: https://github.com/ouknik/otp_phone_verify
repository: https://github.com/ouknik/otp_phone_verify
issue_tracker: https://github.com/ouknik/otp_phone_verify/issues

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  pinput: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

topics:
  - otp
  - phone-verification
  - authentication
  - sms
  - whatsapp
